# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btetzcI4NTuvD4O9-jGBv4ZNfYq-bATR
"""

import pandas as pd
import matplotlib.pyplot as plt


tabela = pd.read_csv('/content/drive/MyDrive/Datasets/colorretal.csv')
print(tabela.columns)

tabela.head(50)

plt.plot(tabela["SEXO"], tabela["obito_geral"])
plt.show()